account/urls.py
from django.urls import path
# from .views import user_login
from django.contrib.auth import views as auth_views





urlpatterns = [
    # path('login/', user_login, name='login')
    path('login/', auth_views.LoginView.as_view(),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(),
         name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(),
         name='password_change'),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('password_reset/done', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('reset/<uid64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from . import views



app_name = 'blog'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls')),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishfManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    object = models.Manager()
    published = PublishfManager()



    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug
        ])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments')

    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f"Comment by {self.author} on {self.post}"

account/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'author', 'body']


class EmailForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .forms import LoginForm
from django.contrib.auth import views as auth_views



#
# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request,
#                                 usernamee=cd['username'],
#                                 password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return HttpResponse('Authenticated successfully!')
#                 else:
#                     return HttpResponse('Disabled account')
#             else:
#                 return HttpResponse('Invalid login ')
#     else:
#         form = LoginForm()
#
#     return render(request, 'account/login.html', {'form': form})

blog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import PostForm, EmailForm, CommentForm
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required

@login_required
def create_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('blog:post_list')
    return render(request, 'blog/post/create.html', {'form': form})



def post_list(request):
    object_list = Post.object.all()
    paginator = Paginator(object_list, 2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'posts': posts, 'page': page})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'




def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)

    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'new_comment': new_comment})


@login_required
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']}({cd['email']}), recomends you reading "\
                      f"{post.title}"
            message = f"Read '{post.title}' at {post_url}" \
                      f"where {cd['name']} comment {cd['comments']}"
            send_mail(subject, message, 'myrzakanovsultan0@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/base.html
{% load static %}


<html lang="en">
<head>

    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<div id='content'>
    {% block content %}
    {% endblock %}
</div>
<div id='sidebar'>
    <h2>My blog</h2>
    <p>This is my blog</p>
    <p>
    <a href="{% url 'blog:create_post' %}">Create</a>
    </p>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
        <div><a href="{% url 'password_change' %}">Change password</a>
    {% else %}
        <a href="{% url 'login' %}">Log In</a><p>
        <a href="{% url 'password_reset' %}">Forgotten now</a>
</p>
    {% endif %}
        </div>
</div>
<body>

</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}


        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}

    </span>

</div>

blog/templates/blog/post/create.html
{% extends 'blog/base.html' %}
{% block title %}
        <h1>Create post</h1>
{% endblock %}


{% block content %}
<h2>NEW POST</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}

{{ post.title }}

{% endblock %}



{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>


    {% with comment.count as total_comments %}
        <h2>{{ total_comments }} comment {{total_comments|pluralize }}</h2>
    {% endwith %}



    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.author }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>
            There are no comments
        </p>
    {% endfor %}



    {% if new_comment %}
        <h2>
            Your comment has been added
        </h2>

    {% else %}
        <h2>
            Add new comment
        </h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p>
                <input type="submit" value="Add comment">
            </p>
        </form>

    {% endif %}

{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}
<h1>My blog</h1>
{% endblock %}
{% block content %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>

<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
{% endfor %}
    {% include 'blog/pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}
Share s post
{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}</p>
    {% else%}
        <H1>Share "{{ post.title }}" by e-mail</H1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sent e-mail">
        </form>
    {% endif %}
{% endblock %}